In [27]:
import numpy as np
import pandas as pd
train_data_path = "/Users/hongpite/Desktop/就业/kaggle/Titanic_data/train.csv"
test_data_path = "/Users/hongpite/Desktop/就业/kaggle/Titanic_data/test.csv"
gender_test_path = "/Users/hongpite/Desktop/就业/kaggle/Titanic_data/gender_submission.csv"

In [28]:
train_data = pd.read_csv(train_data_path)
test_data = pd.read_csv(test_data_path)
gender_date = pd.read_csv(gender_test_path)

In [5]:
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [8]:
test_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [29]:
gender_date.head()

   PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

In [ ]:
women = train_data.loc[train_data.Sex == "female"]["Survived"]
rate_women = sum(women)/len(women)
print("% of women who survived:", rate_women)

# 我对于df，要统计里面的女性数量，则生成是否为女性的mask
# df["Sex"] == "female" 这会得到True False的mask
# 然后将其放入women = df.loc[mask]，则能挑出女性的那些数据，构建新的表格
# 然后计算len(women)得到总女性数量
# 对于存活的，我们可以women["Survived"] 得到存活的那列数据
# 那列数据正好存活是1，死亡是0，也是一种mask
# 然后sum就得到了存活的数量

% of women who survived: 0.7420382165605095

In [15]:
men = train_data.loc[train_data.Sex == 'male']["Survived"]
rate_men = sum(men)/len(men)

print("% of men who survived:", rate_men)

% of men who survived: 0.18890814558058924

In [17]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [25]:
from sklearn.ensemble import RandomForestClassifier

y = train_data["Survived"]

features = ["Pclass", "Sex", "SibSp", "Parch"]
X = pd.get_dummies(train_data[features])
X_test = pd.get_dummies(test_data[features])

# df[col]得到的是原始列
# get_dummies就是把文本类特征转化为0/1数值的独热编码

model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=1)
model.fit(X, y)
predictions = model.predict(X_test)

output = pd.DataFrame({'PassengerId': test_data["PassengerId"], 'Survived': predictions})
# 创建一个新的df，使用字典创建
# 字典的第一个key是ID，value是pd.Series 第二个是Survived，value是array

output.to_csv('/Users/hongpite/Desktop/就业/kaggle/Titanic_data/submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!